CREATE TABLE Врач (
ID INT PRIMARY KEY,
Фамилия VARCHAR(255) NOT NULL,
Имя VARCHAR(255) NOT NULL,
Отчество VARCHAR(255) NOT NULL,
Специальность VARCHAR(100) NOT NULL,
Категория VARCHAR(50) NOT NULL,
Адрес_работы VARCHAR(255) NOT NULL,
Телефон VARCHAR(20) NOT NULL,
Email VARCHAR(100) NOT NULL
);
